name: CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11, 3.13]
        mypy-version: [1.0, 1.18]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies (including dev)
        run: poetry install --with dev

      - name: Install specific mypy version
        run: poetry run pip install --force-reinstall mypy==${{ matrix.mypy-version }}

      - name: Run mypy
        run: poetry run mypy .

      - name: Run pytest
        run: poetry run pytest
